# Generated by Django 3.1 on 2020-08-28 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0002_auto_20200824_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commission',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=50.0, max_digits=6),
        ),
    ]
